<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Db\ResultSet\ResultSetInterface $productos
 */
?>

<div class="container" style="min-height: 100vh; background-color: rgb(240,240,240)">
      <nav aria-label="breadcrumb mt-5">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= $this->url('application', ['action' => 'index']) ?>">Inicio</a></li>
            <li class="breadcrumb-item active" aria-current="page">Base de Datos</li>
        </ol>
    </nav>
  <div class="ms-5 ps-5 pe-5 pb-5 pt-2">
    <a href="<?= $this->url('application', ['action' => 'index']) ?>" class="btn btn-dark p-2"><-</a>
    <span class="fs-2 ms-3">Base de Datos</span>
  </div>

  <div class="d-flex justify-content-center mb-4">
    <div style="max-width:300px">
      <form method="post"
            action="<?= $this->url('application', ['action' => 'insertar-ejemplo']) ?>">
        <button class="btn btn-dark p-4 w-100">
          Insertar producto de ejemplo
        </button>
      </form>

      <form method="post"
            action="<?= $this->url('application', ['action' => 'borrar-todo']) ?>">
        <button class="btn btn-danger p-4 w-100 mt-3">
          Eliminar todos los registros
        </button>
      </form>
    </div>
  </div>

  <div class="container">
    <table class="table table-striped table-bordered bg-white">
      <thead class="table-dark">
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Precio</th>
          <th>Categoría</th>
        </tr>
      </thead>
      <tbody>
        <?php if (count($productos) === 0): ?>
          <tr>
            <td colspan="4" class="text-center">No hay registros</td>
          </tr>
        <?php else: ?>
          <?php foreach ($productos as $producto): ?>
            <tr>
              <td><?= $producto['id'] ?></td>
              <td><?= $producto['nombre'] ?></td>
              <td><?= $producto['precio'] ?></td>
              <td><?= $producto['categoria_id'] ?></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>
</div>
