<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Db\ResultSet\ResultSetInterface $usuarios
 */
?>

<div class="container" style="height: 100vh; background-color: rgb(240,240,240)">

    <nav aria-label="breadcrumb mt-5">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= $this->url('application', ['action' => 'index']) ?>">Inicio</a></li>
            <li class="breadcrumb-item active" aria-current="page">Crud Segunda Evaluación</li>
        </ol>
    </nav>


  <div class="ms-5 ps-5 pe-5 pb-5 pt-2">
    <a href="<?= $this->url('application', ['action' => 'index']) ?>" class="btn btn-dark p-2"><-</a>
    <span class="title mt-5 text-center fs-2 ms-3">Crud Segunda Evaluación</span>
  </div>

  <div class="container">
    <a href="<?= $this->url('application', ['action' => 'addUsuario']) ?>" class="btn btn-dark">
      Agregar Nuevo Usuario
    </a>

    <table class="table table-striped table-bordered bg-white">
      <thead class="table-dark">
        <tr>
          <th>Nombre</th>
          <th>Apellido Paterno</th>
          <th>Apellido Materno</th>
          <th>Telefono</th>
          <th>Correo</th>
          <th>Nacimiento</th>
        </tr>
      </thead>
      <tbody>
        <?php if (count($usuarios) === 0): ?>
          <tr>
            <td colspan="6" class="text-center">No hay registros</td>
          </tr>
        <?php else: ?>
          <?php foreach ($usuarios as $usuario): ?>
            <tr>
              <td><?= $usuario['nombre'] ?></td>
              <td><?= $usuario['apellido_pat'] ?></td>
              <td><?= $usuario['apellido_mat'] ?></td>
              <td><?= $usuario['telefono'] ?></td>
              <td><?= $usuario['correo'] ?></td>
              <td><?= $usuario['nacimiento'] ?></td>
            </tr>
          <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
  </div>
</div>